# healenium.properties
heal-enabled=true
score-threshold=0.7
selector-usage-limit=10
backend-host=http://localhost:7878

#heal-enabled: Enables/disables healing.
#score-threshold: Minimum score for healed locator acceptance.
#selector-usage-limit: Max times a healed selector is reused.
#backend-host: Healenium backend URL (if using backend)